### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: ./output/sft_lora_llama3-8b
template: llama3
trust_remote_code: true
resize_vocab: false

### export
export_dir: ./output/sft_merged_llama3-8b
export_size: 5
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false
