### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: google/gemma-3-4b-it
adapter_name_or_path: ./output/sft_lora_gemma3-4b
template: gemma3
trust_remote_code: true
resize_vocab: false

### export
export_dir: ./output/sft_merged_gemma3-4b
export_size: 5
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false
